xreinforcedRT : reinforcedRT_ExpEnhPerf_stepsize.cpp
	g++ -ggdb -Wall -O3 -o xreinforcedRT reinforcedRT_ExpEnhPerf_stepsize.cpp -fopenmp -lgsl -lgslcblas 

clean :
	rm xreinforcedRT

cleanout:
	rm allele_distrib*
	rm branch.txt
	rm data_work_alloc*.txt
	rm f_dist*.txt
	rm header*.txt
	rm lastgen*.txt
