xreinforcedRT : reinforcedRT_ExpEnhPerf_stepsize.cpp
	g++ -ggdb -Wall -O3 -o xreinforcedRT reinforcedRT_ExpEnhPerf_stepsize.cpp -fopenmp -lgsl -lgslcblas 

clean :
	rm xreinforcedRT

cleanout:
	rm -f data_work_alloc*.txt
	rm -f f_dist*.txt
	rm -f header*.txt
	rm -f lastgen*.txt
	rm -f allele_distrib*
	rm -f branch.txt
